### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by ChaofengWu0** [XJC-git/CS305-LabAssignment2#2]
请问这次作业的编码是用的什么呢？ utf-8无法解码下面第一张图的bytes流，使用gbk编码也不行，使用’unicode_escape‘编码可以得到结果，但是在_parse_reply中，TODO写的是要求我们从packet中读出sequence，type，code信息，可是使用’unicode_escape‘得到的结果是第二张图的样子，看起来无法得到sequence，type的信息
![image](https://user-images.githubusercontent.com/82070917/206836318-2e9a7188-3e50-40fb-ab6f-7330319cded8.png)
![image](https://user-images.githubusercontent.com/82070917/206836451-d7cdbfd4-65fc-483b-9f32-e44a2b5ebad9.png)

**Comment by XJC-git** [comment]
这是十六进制bytes, 可以使用struct.unpack函数得到所需参数

**Comment by ChaofengWu0** [comment]
明白了，谢谢👍
